package com.mangroo.temperature.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.util.Date;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Temperature")
public class Temperature {

    private String id;
    private String name;
    private float temperatureReading;
    private Date timestamp;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public float getTemperatureReading() {
        return temperatureReading;
    }

    @DynamoDBAttribute
    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTemperatureReading(float temperatureReading) {
        this.temperatureReading = temperatureReading;
    }

    public void setName(String name) {
        this.name = name;
    }
}
